import pytest
import os
import sys
import pandas as pd

@pytest.mark.regression
def test_csv_logging_schema(project_root, mock_results_dir, monkeypatch):
    """
    Regression Test:
    Ensures that the CSV logs generated by the simulation engine strictly contain 
    the columns expected by all downstream notebook/plotting scripts.
    """
    sys.path.insert(0, project_root)
    
    from configs import config
    # Override settings for a fast run
    monkeypatch.setattr(config, "N", 2, raising=False)
    monkeypatch.setattr(config, "SIM_TIME_S", 0.1, raising=False)
    monkeypatch.setattr(config, "MAC_PROTOCOL", "TDMA", raising=False)
    monkeypatch.setattr(config, "SWEEP_MIN_PPS", 100, raising=False)
    monkeypatch.setattr(config, "SWEEP_MAX_PPS", 100, raising=False)
    monkeypatch.setattr(config, "SWEEP_STEPS", 1, raising=False)
    
    from simulator_ui.engine import SimulationEngine
    
    engine = SimulationEngine()
    engine.output_dir = mock_results_dir
    engine.reset()
    while engine.sim_time < config.SIM_TIME_S:
        engine.tick()
        
    run_dir = engine.export(base_results_dir=mock_results_dir)

    # Read the output CSV
    csv_file = os.path.join(run_dir, "csv", "mobility_positions.csv")
    assert os.path.isfile(csv_file), "mobility_positions.csv was not generated."

    # Validate schema
    df = pd.read_csv(csv_file)
    expected_columns = {
        "timestamp", "uav_id", "x", "y", "z", "vx", "vy", "vz", "speed"
    }
    actual_columns = set(df.columns)
    missing_columns = expected_columns - actual_columns
    assert not missing_columns, f"Regression Issue: CSV is missing strictly required columns: {missing_columns}"
